#!/usr/bin/env python3
# Copyright (c) 2026 DirectJob Scout contributors
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.

"""generate-seo-pages.py — fan out cities × roles into seo-pages.json.

Phase 7 tracker item #62: "SEO content cadence: 1 indexable job-alert
page per major role × major city (10 cities × 20 roles = 200 pages)."

The engineering side of the SEO pages already exists (#17). This
script just fans out a small operator-edited config (cities + roles)
into the corresponding ``seo-pages.json`` entries. Run after editing
``deploy/seo-pages-input.json`` to refresh.

Usage:
    ./scripts/generate-seo-pages.py                    # writes <data dir>/seo-pages.json
    ./scripts/generate-seo-pages.py --dry-run          # prints to stdout
    ./scripts/generate-seo-pages.py --input PATH       # custom input file
    ./scripts/generate-seo-pages.py --output PATH      # custom output file

Input file shape::

    {
        "cities": [{"slug": "berlin", "label": "Berlin"}, {"slug": "munich", "label": "Munich"}],
        "roles": [
            {"slug": "data-engineer", "label": "Data engineer"},
            {"slug": "product-manager", "label": "Product manager"},
        ],
        "intro_template": "DirectJob Scout watches direct career pages plus the major aggregators for {role} roles in {city}. No feed, no algorithm, no recruiter messages.",
    }

Output is ``deploy/seo-pages.json.example``-shaped — an object with a
``pages`` array and a ``_doc`` string. Cross-product is straightforward
(N cities × M roles = N×M pages). The script de-duplicates by slug so
re-running with the same input is a no-op.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent


def fan_out(payload: dict[str, Any]) -> list[dict[str, str]]:
    cities = payload.get("cities") or []
    roles = payload.get("roles") or []
    template = (
        payload.get("intro_template")
        or "DirectJob Scout watches direct career pages plus the major aggregators "
        "for {role} roles in {city}."
    )
    pages: list[dict[str, str]] = []
    seen: set[str] = set()
    for city in cities:
        if not isinstance(city, dict):
            continue
        city_slug = str(city.get("slug") or "").strip()
        city_label = str(city.get("label") or "").strip()
        if not city_slug or not city_label:
            continue
        for role in roles:
            if not isinstance(role, dict):
                continue
            role_slug = str(role.get("slug") or "").strip()
            role_label = str(role.get("label") or "").strip()
            if not role_slug or not role_label:
                continue
            slug = f"{role_slug}-{city_slug}"
            if slug in seen:
                continue
            seen.add(slug)
            pages.append(
                {
                    "slug": slug,
                    "title": f"{role_label} jobs in {city_label}",
                    "role": role_label,
                    "city": city_label,
                    "intro": template.format(role=role_label, city=city_label),
                }
            )
    return pages


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "--input",
        default=str(REPO_ROOT / "deploy" / "seo-pages-input.json.example"),
        help="Input JSON with cities + roles (default: deploy/seo-pages-input.json.example)",
    )
    parser.add_argument(
        "--output",
        default=str(REPO_ROOT / "deploy" / "seo-pages.json.example"),
        help="Output JSON in seo-pages.json shape (default: deploy/seo-pages.json.example)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of writing the output file",
    )
    args = parser.parse_args(argv)

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"generate-seo-pages: input not found: {input_path}", file=sys.stderr)
        return 2
    try:
        payload = json.loads(input_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        print(f"generate-seo-pages: bad input: {error}", file=sys.stderr)
        return 2

    pages = fan_out(payload)
    out = {
        "_doc": (
            f"Generated by scripts/generate-seo-pages.py from {input_path.name}. "
            "Operator edits the input config + re-runs to refresh. Do not hand-edit "
            "this file (changes will be overwritten on the next regeneration)."
        ),
        "pages": pages,
    }
    rendered = json.dumps(out, indent=2, ensure_ascii=False) + "\n"
    if args.dry_run:
        sys.stdout.write(rendered)
        return 0
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    print(
        f"generate-seo-pages: wrote {output_path} ({len(pages)} pages)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
